version: '3'
services:
  frontend:
    build: ./frontend
    container_name: cc-admin-frontend
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - backend
  backend:
    build: ./backend
    container_name: cc-admin-backend
    restart: always
    ports:
      - "8080:8080"
    environment:
      - DB_HOST=database
    env_file:
      - ./backend/.env
    volumes:
      - ./backend/uploads:/app/uploads
    depends_on:
      - database
  database:
    image: postgres:15.4-alpine3.18
    restart: always
    container_name: cc-admin-database
    env_file:
      - ./database/.env
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./database/pgdata:/var/lib/postgresql/data
  adminer:
    image: adminer
    container_name: cc-admin-adminer
    restart: always
    ports:
      - 8081:8080
